Repository weaveworks/ignite, pull requests merged in 2019-10, with the labels that each got.

#468 make autogen tidy
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/modules.txt
Labels: area/dependency

#467 Fix all containerd functional tests
  pkg/runtime/containerd/client_test.go
Labels: area/runtime, area/testing, kind/cleanup

#471 Ensure CNI bin dir exists before installing
  docs/installation.md
Labels: kind/bug, kind/documentation

#469 use ssh discover technique to check if SSH service is really run…
  cmd/ignite/run/start.go
Labels: kind/bug
