Repository weaveworks/ignite, pull requests merged in 2019-07, with the labels that each got.

#221 Client and Storage rework: Recognize multiple API groups
  api/ignite.md
  api/meta.md
  cmd/ignite/run/create.go
  pkg/apis/ignite/v1alpha1/defaults.go
  pkg/apis/ignite/v1alpha1/zz_generated.defaults.go
  pkg/apis/meta/v1alpha1/meta.go
  pkg/client/client.go
  pkg/client/client_dynamic.go
  pkg/client/client_resource_template.go
  pkg/client/zz_generated.client_image.go
  pkg/client/zz_generated.client_kernel.go
  pkg/client/zz_generated.client_vm.go
  pkg/metadata/imgmd/imgmd.go
  pkg/metadata/kernmd/kernmd.go
  pkg/metadata/metadata.go
  pkg/metadata/vmmd/vmmd.go
  pkg/operations/import.go
  pkg/storage/cache.go
  pkg/storage/filterer/filterer.go
  pkg/storage/gitops/rawstorage.go
  pkg/storage/serializer/serializer.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: kind/enhancement, kind/refactor, priority/important-soon

#226 Rename GitStorage into ManifestStorage
  pkg/gitops/gitdir/gitdir.go
  pkg/gitops/gitops.go
  pkg/storage/gitops/storage.go
  pkg/storage/manifest/rawstorage.go
  pkg/storage/manifest/storage.go
Labels: kind/enhancement, kind/refactor

#227 Support checksum-based Cache invalidation, improve cache's object handling
  docs/dependencies.svg
  pkg/apis/ignite/validation/validation.go
  pkg/client/client_dynamic.go
  pkg/client/client_resource_template.go
  pkg/client/zz_generated.client_image.go
  pkg/client/zz_generated.client_kernel.go
  pkg/client/zz_generated.client_vm.go
  pkg/gitops/gitops.go
  pkg/providers/storage.go
  pkg/storage/cache.go
  pkg/storage/cache/cache.go
  pkg/storage/cache/index.go
  pkg/storage/cache/object.go
  pkg/storage/filterer/filterer.go
  pkg/storage/manifest/rawstorage.go
  pkg/storage/rawstorage.go
  pkg/storage/storage.go
  pkg/util/patch/patch.go
Labels: kind/enhancement, kind/refactor

#111 CNI networking cleanup support, Docker client robustness improvements
  pkg/operations/remove.go
  pkg/operations/start.go
  pkg/runtime/docker/client.go
  pkg/runtime/types.go
  pkg/storage/cache/cache.go
  pkg/storage/cache/index.go
Labels: do-not-merge/wip

#242 Documentation updates and clarifications for the New Storage implementation
  cmd/ignite/cmd/daemon.go
  pkg/storage/sync/storage.go
  pkg/storage/watch/storage.go
  pkg/storage/watch/update/associated.go
  pkg/storage/watch/update/event.go
  pkg/storage/watch/update/file.go
  pkg/storage/watch/update/update.go
  pkg/storage/watch/watch.go
  pkg/util/monitor.go
Labels: kind/cleanup, kind/documentation

#241 Implement read-write GitOps
  cmd/ignite/cmd/gitops.go
  docs/cli/ignite_gitops.md
  pkg/gitops/gitdir/gitdir.go
  pkg/gitops/gitops.go
  pkg/storage/manifest/storage.go
  pkg/storage/sync/storage.go
  pkg/storage/watch/batcher.go
  pkg/storage/watch/batcher_test.go
  pkg/storage/watch/storage.go
  pkg/storage/watch/update/event.go
  pkg/storage/watch/update/event_test.go
  pkg/storage/watch/watch.go
  pkg/storage/watch/watcher_test.go
Labels: kind/enhancement, kind/refactor, priority/important-soon

#244 Actually stop the watcher dispatch thread, better formatting consistency
  pkg/storage/sync/storage.go
  pkg/storage/watch/watch.go
Labels: kind/cleanup, kind/enhancement

#250 Fork v1alpha1 API to become v1alpha2
  Makefile
  api/openapi/openapi_generated.go
  api/openapi/violations.txt
  pkg/apis/ignite/v1alpha2/defaults.go
  pkg/apis/ignite/v1alpha2/doc.go
  pkg/apis/ignite/v1alpha2/json.go
  pkg/apis/ignite/v1alpha2/register.go
  pkg/apis/ignite/v1alpha2/types.go
  pkg/apis/ignite/v1alpha2/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/ignite/v1alpha2/zz_generated.defaults.go
Labels: api/v1alpha2, kind/api-change

#245 Extract watcher, batcher and monitor into pkg/util
  pkg/gitops/gitops.go
  pkg/storage/sync/storage.go
  pkg/storage/watch/batcher.go
  pkg/storage/watch/storage.go
  pkg/storage/watch/update/associated.go
  pkg/storage/watch/update/event_test.go
  pkg/storage/watch/update/file.go
  pkg/storage/watch/update/update.go
  pkg/storage/watch/watch.go
  pkg/storage/watch/watcher_test.go
  pkg/util/sync/batcher.go
  pkg/util/sync/batcher_test.go
  pkg/util/sync/monitor.go
  pkg/util/watcher/event.go
  pkg/util/watcher/filewatcher.go
  pkg/util/watcher/filewatcher_test.go
Labels: kind/refactor, priority/important-soon

#249 Fix image root permissions
  pkg/dmlegacy/vm.go
Labels: kind/bug

#247 Make Ignite use `logrus` everywhere, support setting log level for ignite-spawn and Firecracker
  cmd/ignite-spawn/ignite-spawn.go
  cmd/ignite-spawn/root.go
  cmd/ignite/cmd/cmdutil/errors.go
  cmd/ignite/cmd/completion.go
  cmd/ignite/cmd/daemon.go
  cmd/ignite/cmd/gitops.go
  cmd/ignite/cmd/imgcmd/image.go
  cmd/ignite/cmd/imgcmd/import.go
  cmd/ignite/cmd/imgcmd/rm.go
  cmd/ignite/cmd/inspect.go
  cmd/ignite/cmd/kerncmd/import.go
  cmd/ignite/cmd/kerncmd/kernel.go
  cmd/ignite/cmd/kerncmd/rm.go
  cmd/ignite/cmd/root.go
  cmd/ignite/cmd/version.go
  cmd/ignite/cmd/vmcmd/attach.go
  cmd/ignite/cmd/vmcmd/create.go
  cmd/ignite/cmd/vmcmd/exec.go
  cmd/ignite/cmd/vmcmd/kill.go
  cmd/ignite/cmd/vmcmd/logs.go
  cmd/ignite/cmd/vmcmd/ps.go
  cmd/ignite/cmd/vmcmd/rm.go
  cmd/ignite/cmd/vmcmd/run.go
  cmd/ignite/cmd/vmcmd/ssh.go
  cmd/ignite/cmd/vmcmd/start.go
  cmd/ignite/cmd/vmcmd/stop.go
  cmd/ignite/cmd/vmcmd/vm.go
  cmd/ignite/ignite.go
  pkg/constants/constants.go
  pkg/container/firecracker.go
  pkg/dm/device.go
  pkg/dm/dm.go
  pkg/errutils/errors.go
  pkg/gitops/gitdir/gitdir.go
  pkg/gitops/gitops.go
  pkg/logs/logs.go
  pkg/metadata/id.go
  pkg/operations/import.go
  pkg/operations/remove.go
  pkg/operations/start.go
  pkg/source/docker.go
Labels: kind/enhancement, kind/feature, priority/important-longterm

#252 Refactor pkg/providers
  cmd/ignite-spawn/ignite-spawn.go
  cmd/ignite/cmd/daemon.go
  cmd/ignite/ignite.go
  hack/cobra.go
  pkg/network/cni/cni.go
  pkg/network/cni/types.go
  pkg/network/types.go
  pkg/providers/client.go
  pkg/providers/client/client.go
  pkg/providers/cni/cni.go
  pkg/providers/docker/runtime.go
  pkg/providers/ignite/providers.go
  pkg/providers/network.go
  pkg/providers/providers.go
  pkg/providers/runtime.go
  pkg/providers/spawn/provider.go
  pkg/providers/storage.go
  pkg/providers/storage/storage.go
  pkg/storage/cache/cache.go
  pkg/storage/storage.go
  pkg/storage/sync/storage.go
  pkg/storage/watch/storage.go
Labels: kind/refactor
