Repository weaveworks/ignite, pull requests merged in 2019-09, with the labels that each got.

#412 Add an e2e for ignite run
  Makefile
  e2e/run_test.go
  go.mod
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/gotest.tools/LICENSE
  vendor/gotest.tools/assert/assert.go
  vendor/gotest.tools/assert/cmp/compare.go
  vendor/gotest.tools/assert/cmp/result.go
  vendor/gotest.tools/assert/result.go
  vendor/gotest.tools/internal/difflib/LICENSE
  vendor/gotest.tools/internal/difflib/difflib.go
  vendor/gotest.tools/internal/format/diff.go
  vendor/gotest.tools/internal/format/format.go
  vendor/gotest.tools/internal/source/defers.go
  vendor/gotest.tools/internal/source/source.go
  vendor/modules.txt
Labels: area/testing

#411 Detect available containerd-shim versions defaulting to legacy linux runtime
  go.mod
  go.sum
  pkg/runtime/containerd/client.go
  pkg/runtime/containerd/client_test.go
  vendor/github.com/containerd/containerd/api/services/ttrpc/events/v1/doc.go
  vendor/github.com/containerd/containerd/api/services/ttrpc/events/v1/events.pb.go
  vendor/github.com/containerd/containerd/api/services/ttrpc/events/v1/events.proto
  vendor/github.com/containerd/containerd/pkg/ttrpcutil/client.go
  vendor/github.com/containerd/containerd/pkg/ttrpcutil/client_unix.go
  vendor/github.com/containerd/containerd/pkg/ttrpcutil/client_windows.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/publisher.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim_darwin.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim_freebsd.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim_linux.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim_unix.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim_windows.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/util.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/util_unix.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/util_windows.go
  vendor/github.com/containerd/containerd/runtime/v2/task/doc.go
  vendor/github.com/containerd/containerd/runtime/v2/task/shim.pb.go
  vendor/github.com/containerd/containerd/runtime/v2/task/shim.proto
  vendor/github.com/containerd/containerd/sys/reaper/reaper_unix.go
  vendor/github.com/containerd/go-runc/.travis.yml
  vendor/github.com/containerd/go-runc/LICENSE
  vendor/github.com/containerd/go-runc/README.md
  vendor/github.com/containerd/go-runc/command_linux.go
  vendor/github.com/containerd/go-runc/command_other.go
  vendor/github.com/containerd/go-runc/console.go
  vendor/github.com/containerd/go-runc/container.go
  vendor/github.com/containerd/go-runc/events.go
  vendor/github.com/containerd/go-runc/io.go
  vendor/github.com/containerd/go-runc/io_unix.go
  vendor/github.com/containerd/go-runc/io_windows.go
  vendor/github.com/containerd/go-runc/monitor.go
  vendor/github.com/containerd/go-runc/runc.go
  vendor/github.com/containerd/go-runc/utils.go
  vendor/modules.txt
Labels: kind/bug, kind/enhancement, priority/critical-urgent

#415 quick fix typo umount as unmount in preflight check
  pkg/constants/dependencies.go
Labels: kind/bug

#417 Update Makefile for containerd with overridable commands
  Makefile
Labels: kind/bug, kind/refactor

#416 improve preflight check and add a containerd test case for ignite run
  e2e/run_test.go
  pkg/constants/dependencies.go
  pkg/preflight/checkers/checks.go
Labels: area/runtime, area/testing

#422 e2e docker+cni and curl google.com
  e2e/run_test.go
Labels: area/networking, area/testing

#426 Make getIPChains more precise and less failure-prone
  pkg/network/cni/cni.go
Labels: area/dependency, area/networking, kind/bug

#425 Store e2e command output /w errors + remove variable sleep
  Makefile
  e2e/run_test.go
Labels: area/testing

#430 backport: skip root requirement for ignite version
  cmd/ignite/cmd/root.go
  cmd/ignite/ignite.go
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/modules.txt
Labels: kind/backport, kind/enhancement

#429 implement ssh wait for a VM
  cmd/ignite/run/start.go
Labels: area/networking, kind/enhancement

#435 Load all images into containerd
  Makefile
Labels: kind/enhancement

#441 Fix containerd resolv.conf + DHCP behavior
  pkg/operations/start.go
  pkg/resolvconf/resolvconf.go
  pkg/resolvconf/resolvconf_test.go
  pkg/runtime/containerd/client.go
  pkg/runtime/docker/client.go
  pkg/runtime/types.go
  pkg/util/fs.go
Labels: area/networking, kind/bug

#442 Chain firewall plugin to fix routing for default CNI bridge
  pkg/network/cni/cni.go
Labels: area/networking

#444 improve rm docs
  docs/usage.md
Labels: kind/documentation

#453 Bump indirect dependency on klog
  go.mod
  go.sum
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: area/dependency

#454 Make documented install safer for docker-ce users
  docs/installation.md
Labels: area/runtime, kind/bug, kind/documentation

#452 Fix test breakage introduced by 585d77f
  pkg/runtime/containerd/client_test.go
Labels: area/testing, kind/bug

#451 backport: implement ssh wait for a VM
  cmd/ignite/run/start.go
Labels: area/networking, kind/backport

#456 0.5.x - Bump indirect dependency on klog
  go.mod
  go.sum
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: area/dependency

#460 Change default CNI network name, bridge name, and subnet
  pkg/network/cni/cni.go
Labels: area/networking

#461 Teardown IPMasq rules for all actual configured bridges instead of using the hardcoded default string
  pkg/network/cni/cni.go
Labels: area/networking, kind/bug
