Repository weaveworks/ignite, pull requests merged in 2019-08, with the labels that each got.

#270 Add an awesome-ignite list for ignite
  README.md
  docs/awesome.md
  docs/index.rst
Labels: kind/documentation

#271 Support directories as well with the `--copy-files` flag
  cmd/ignite/cmd/vmcmd/create.go
  go.mod
  go.sum
  pkg/util/fs.go
  vendor/github.com/otiai10/copy/.gitignore
  vendor/github.com/otiai10/copy/.travis.yml
  vendor/github.com/otiai10/copy/LICENSE
  vendor/github.com/otiai10/copy/README.md
  vendor/github.com/otiai10/copy/copy.go
  vendor/github.com/otiai10/copy/go.mod
  vendor/github.com/otiai10/copy/go.sum
  vendor/modules.txt
Labels: area/UX, kind/enhancement, kind/feature

#285 Clean up ignite-spawn networking, don't depend on `errors` package
  Dockerfile
  pkg/container/dhcp.go
  pkg/container/network.go
Labels: kind/cleanup

#275 Support external volumes (block devices) in Ignite VMs
  Dockerfile
  cmd/ignite/cmd/cmdutil/flags.go
  cmd/ignite/cmd/cmdutil/networkflag.go
  cmd/ignite/cmd/cmdutil/ociflag.go
  cmd/ignite/cmd/cmdutil/sizeflag.go
  cmd/ignite/cmd/cmdutil/sshflag.go
  cmd/ignite/cmd/cmdutil/volumeflag.go
  cmd/ignite/cmd/vmcmd/create.go
  cmd/ignite/run/create.go
  cmd/ignite/run/start.go
  docs/api/ignite_v1alpha1.md
  docs/api/ignite_v1alpha2.md
  docs/cli/ignite/ignite_create.md
  docs/cli/ignite/ignite_run.md
  docs/cli/ignite/ignite_vm_create.md
  docs/cli/ignite/ignite_vm_run.md
  pkg/apis/ignite/types.go
  pkg/apis/ignite/v1alpha1/conversion.go
  pkg/apis/ignite/v1alpha1/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/types.go
  pkg/apis/ignite/v1alpha2/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/ignite/validation/storage.go
  pkg/apis/ignite/validation/validation.go
  pkg/apis/ignite/zz_generated.deepcopy.go
  pkg/constants/vm.go
  pkg/container/firecracker.go
  pkg/dmlegacy/fstab.go
  pkg/dmlegacy/vm.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/violations.txt
  pkg/operations/reconcile/reconcile.go
  pkg/operations/start.go
  pkg/runtime/docker/client.go
  pkg/runtime/types.go
  pkg/storage/watch/update/event.go
  pkg/util/fs.go
  pkg/util/math.go
  pkg/util/util.go
Labels: kind/api-change, kind/design, kind/feature

#292 Replace `vm.status.state` with `vm.status.running`
  Makefile
  cmd/ignite-spawn/ignite-spawn.go
  cmd/ignite/run/ps.go
  docs/api/ignite_v1alpha1.md
  docs/api/ignite_v1alpha2.md
  pkg/apis/ignite/helpers.go
  pkg/apis/ignite/types.go
  pkg/apis/ignite/v1alpha1/conversion.go
  pkg/apis/ignite/v1alpha1/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/defaults.go
  pkg/apis/ignite/v1alpha2/types.go
  pkg/apis/ignite/v1alpha2/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/zz_generated.defaults.go
  pkg/apis/ignite/validation/validation.go
  pkg/filter/vm.go
  pkg/openapi/openapi_generated.go
  pkg/operations/reconcile/reconcile.go
Labels: kind/api-change, kind/design

#296 Add `vm.status.startTime` to track the VM's uptime externally
  cmd/ignite-spawn/ignite-spawn.go
  cmd/ignite/run/ps.go
  docs/api/ignite_v1alpha2.md
  pkg/apis/ignite/types.go
  pkg/apis/ignite/v1alpha1/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/types.go
  pkg/apis/ignite/v1alpha2/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/ignite/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operations/start.go
Labels: kind/api-change, kind/design

#299 Support configuring the bind address and protocol for port binds
  docs/api/meta_v1alpha1.md
  pkg/apis/ignite/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/ignite/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/ignite/validation/validation.go
  pkg/apis/ignite/zz_generated.deepcopy.go
  pkg/apis/meta/v1alpha1/net.go
  pkg/apis/meta/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/runtime/docker/client.go
  pkg/runtime/docker/port.go
Labels: do-not-merge/wip, kind/api-change, kind/design, kind/enhancement

#300 Runtime state set by Ignite (StartVM), ignite-spawn only handles shutdown
  cmd/ignite-spawn/ignite-spawn.go
  pkg/container/dhcp.go
  pkg/operations/start.go
  pkg/runtime/docker/client.go
  pkg/runtime/types.go
Labels: kind/design, kind/refactor

#305 Storage cleanup: document RawStorage, make RawStorage and MappedRawStorage more compatible
  Makefile
  docs/api/meta_v1alpha1.md
  go.mod
  go.sum
  pkg/apis/meta/v1alpha1/meta.go
  pkg/providers/storage/storage.go
  pkg/storage/key.go
  pkg/storage/manifest/storage.go
  pkg/storage/mappedrawstorage.go
  pkg/storage/rawstorage.go
  pkg/storage/storage_test.go
  pkg/storage/watch/storage.go
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/json-iterator/go/adapter.go
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/json-iterator/go/iter_skip.go
  vendor/github.com/json-iterator/go/reflect_native.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/stream_float.go
  vendor/modules.txt
Labels: kind/cleanup, kind/enhancement, kind/refactor

#308 Improve the CNI implementation, and documentation
  README.md
  docs/networking.md
  pkg/network/cni/cni.go
  pkg/network/docker/docker.go
  pkg/network/types.go
  pkg/operations/remove.go
  pkg/operations/start.go
  pkg/providers/cni/cni.go
  pkg/providers/docker/runtime.go
  pkg/providers/ignite/providers.go
  pkg/providers/ignited/providers.go
  pkg/providers/providers.go
  vendor/modules.txt
Labels: kind/enhancement

#307 OCI image status representation redesign
  docs/api/ignite_v1alpha1.md
  docs/api/ignite_v1alpha2.md
  docs/api/meta_v1alpha1.md
  go.mod
  pkg/apis/ignite/types.go
  pkg/apis/ignite/v1alpha1/conversion.go
  pkg/apis/ignite/v1alpha1/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/types.go
  pkg/apis/ignite/v1alpha2/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/ignite/zz_generated.deepcopy.go
  pkg/apis/meta/v1alpha1/image.go
  pkg/apis/meta/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/violations.txt
  pkg/source/docker.go
Labels: kind/api-change, kind/design, kind/enhancement

#313 issue #75: docs on footloose/ignite integration
  docs/footloose-ignite-integration.md
  docs/footloose.k8s.yaml
Labels: kind/documentation

#311 OCIImageClaim -> OCIRef, simplify by naming the field `oci`
  cmd/ignite/cmd/vmcmd/create.go
  cmd/ignite/run/create.go
  cmd/ignite/run/ps.go
  docs/api/ignite_v1alpha1.md
  docs/api/ignite_v1alpha2.md
  docs/api/meta_v1alpha1.md
  pkg/apis/ignite/helpers.go
  pkg/apis/ignite/types.go
  pkg/apis/ignite/v1alpha1/conversion.go
  pkg/apis/ignite/v1alpha1/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/defaults.go
  pkg/apis/ignite/v1alpha2/types.go
  pkg/apis/ignite/v1alpha2/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/ignite/v1alpha2/zz_generated.defaults.go
  pkg/apis/ignite/validation/validation.go
  pkg/apis/ignite/zz_generated.deepcopy.go
  pkg/apis/meta/v1alpha1/image.go
  pkg/openapi/openapi_generated.go
  pkg/operations/import.go
  pkg/operations/lookup/lookup.go
  pkg/operations/reconcile/reconcile.go
Labels: kind/api-change, kind/design, kind/enhancement, kind/refactor

#320 Fix `ignite rm -f` for a running VM without `--debug`
  pkg/operations/remove.go
  pkg/operations/start.go
  pkg/runtime/docker/client.go
Labels: kind/bug

#321 Fix uptime formatting in `ps`, simplify status formatting
  cmd/ignite/run/ps.go
  docs/api/meta_v1alpha1.md
  pkg/apis/meta/v1alpha1/time.go
Labels: kind/cleanup

#323 Wrap the strict deserializer as a codec
  pkg/storage/serializer/serializer.go
Labels: kind/cleanup

#325 Format and improve the Read The Docs site
  .grenrc.js
  docs/cloudprovider.md
  docs/footloose-ignite-integration.md
  docs/footloose.k8s.yaml
  docs/footloose.md
  docs/index.rst
  docs/releases/v0.5.0-alpha.1.md
Labels: kind/cleanup

#326 add logo to docs
  docs/index.rst
Labels: kind/documentation

#332 Add TODO to implement `omitempty` for VMNetworkSpec and VMStorageSpec
  docs/api/ignite_v1alpha2.md
  pkg/apis/ignite/types.go
  pkg/apis/ignite/v1alpha2/types.go
  pkg/openapi/openapi_generated.go
Labels: kind/cleanup

#331 add simple CODEOWNERS file
  .github/CODEOWNERS
Labels: kind/documentation

#330 docs: packet and azure
  docs/cloudprovider.md
Labels: kind/documentation

#324 Documentation updates for v0.5.0
  CONTRIBUTING.md
  README.md
  docs/FAQ.md
  docs/api/ignite_v1alpha1.md
  docs/declarative-config.md
  docs/dependencies.md
  docs/devel.md
  docs/gitops.md
  docs/index.rst
  docs/installation.md
  docs/my-vm.yaml
  docs/networking.md
  gitops/README.md
  gitops/amazonlinux-vm.json
  gitops/ubuntu-vm.yaml
  ignite.iml
  images/kubeadm/README.md
  pkg/apis/ignite/v1alpha1/conversion.go
Labels: documentation/improvement, documentation/out-of-date, kind/documentation

#333 Update the roadmap to reflect the current state
  README.md
  ROADMAP.md
  docs/index.rst
  docs/roadmap.md
Labels: kind/cleanup

#336 Fix ignite-spawn's formatting when performing cleanup on VM metadata
  pkg/util/patch/patch.go
Labels: kind/cleanup, kind/enhancement

#338 Change Read the Docs links to point to the stable branch in main README
  README.md
Labels: documentation/improvement, kind/documentation

#340 Fix GOHOSTARCH propagation, tag development image for the host architecture only
  Makefile
Labels: area/UX, kind/bug, kind/enhancement

#341 FileWatcher: Support internal moves without re-creating and multiple active moves at once
  pkg/storage/sync/storage.go
  pkg/storage/watch/storage.go
  pkg/util/watcher/event.go
  pkg/util/watcher/filewatcher.go
Labels: kind/design, kind/enhancement

#342 Use util.Prefixer in place of manual concatenation, use IGNITE_PREFIX in util.Prefixer
  pkg/apis/ignite/helpers.go
  pkg/constants/constants.go
  pkg/dmlegacy/cleanup/deactivate.go
  pkg/dmlegacy/snapshot.go
  pkg/util/util.go
Labels: kind/cleanup

#347 Split packages so we can extract `gitops-toolkit`
  cmd/ignite-spawn/ignite-spawn.go
  pkg/apis/ignite/scheme/scheme.go
  pkg/gitops/gitops.go
  pkg/providers/manifeststorage/storage.go
  pkg/serializer/serializer.go
  pkg/serializer/serializer_test.go
  pkg/storage/cache/cache.go
  pkg/storage/manifest/storage.go
  pkg/storage/storage.go
  pkg/storage/sync/storage.go
  pkg/storage/watch/storage.go
  pkg/util/patch/patch.go
Labels: kind/enhancement

#349 Simplify the CNI code by vendoring github.com/containerd/go-cni
  go.mod
  go.sum
  pkg/network/cni/cni.go
  pkg/network/cni/types.go
  pkg/network/docker/docker.go
  pkg/network/types.go
  vendor/github.com/containerd/go-cni/.travis.yml
  vendor/github.com/containerd/go-cni/LICENSE
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/errors.go
  vendor/github.com/containerd/go-cni/helper.go
  vendor/github.com/containerd/go-cni/namespace.go
  vendor/github.com/containerd/go-cni/namespace_opts.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containerd/go-cni/result.go
  vendor/github.com/containerd/go-cni/testutils.go
  vendor/github.com/containerd/go-cni/types.go
  vendor/github.com/containerd/go-cni/vendor.conf
  vendor/modules.txt
Labels: area/dependency, kind/enhancement, kind/refactor

#350 Fix Docker client port mappings by actually exposing them after binding
  pkg/runtime/docker/client.go
  pkg/runtime/docker/port.go
Labels: kind/bug, priority/important-soon

#356 Fix the dependencies for the containerd client
  go.mod
  go.sum
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/registry/api/errcode/errors.go
  vendor/github.com/docker/distribution/registry/api/errcode/handler.go
  vendor/github.com/godbus/dbus/.travis.yml
  vendor/github.com/godbus/dbus/README.markdown
  vendor/github.com/godbus/dbus/auth.go
  vendor/github.com/godbus/dbus/auth_anonymous.go
  vendor/github.com/godbus/dbus/call.go
  vendor/github.com/godbus/dbus/conn.go
  vendor/github.com/godbus/dbus/conn_darwin.go
  vendor/github.com/godbus/dbus/conn_other.go
  vendor/github.com/godbus/dbus/conn_unix.go
  vendor/github.com/godbus/dbus/conn_windows.go
  vendor/github.com/godbus/dbus/decoder.go
  vendor/github.com/godbus/dbus/default_handler.go
  vendor/github.com/godbus/dbus/export.go
  vendor/github.com/godbus/dbus/go.mod
  vendor/github.com/godbus/dbus/object.go
  vendor/github.com/godbus/dbus/server_interfaces.go
  vendor/github.com/godbus/dbus/transport_generic.go
  vendor/github.com/godbus/dbus/transport_nonce_tcp.go
  vendor/github.com/godbus/dbus/transport_unix.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: area/dependency, kind/feature, priority/important-soon

#357 Add openSUSE images
  images/Makefile
  images/opensuse/Dockerfile
Labels: area/ecosystem, kind/feature

#337 Implement the containerd runtime for Ignite
  docs/api/meta_v1alpha1.md
  go.mod
  go.sum
  pkg/apis/ignite/v1alpha1/defaults.go
  pkg/apis/ignite/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/ignite/v1alpha2/defaults.go
  pkg/apis/ignite/v1alpha2/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/ignite/zz_generated.deepcopy.go
  pkg/apis/meta/v1alpha1/image.go
  pkg/apis/meta/v1alpha1/zz_generated.deepcopy.go
  pkg/metadata/metadata.go
  pkg/network/cni/cni.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/violations.txt
  pkg/operations/start.go
  pkg/providers/containerd/runtime.go
  pkg/providers/ignite/providers.go
  pkg/providers/ignited/providers.go
  pkg/providers/providers.go
  pkg/runtime/containerd/client.go
  pkg/runtime/containerd/client_test.go
  pkg/runtime/containerd/resize.go
  pkg/runtime/containerd/signals.go
  pkg/runtime/docker/client.go
  pkg/runtime/types.go
  pkg/source/docker.go
  pkg/source/source.go
  pkg/util/util.go
  vendor/github.com/containerd/console/.travis.yml
  vendor/github.com/containerd/console/LICENSE
  vendor/github.com/containerd/console/README.md
  vendor/github.com/containerd/console/console.go
  vendor/github.com/containerd/console/console_linux.go
  vendor/github.com/containerd/console/console_unix.go
  vendor/github.com/containerd/console/console_windows.go
  vendor/github.com/containerd/console/tc_darwin.go
  vendor/github.com/containerd/console/tc_freebsd.go
  vendor/github.com/containerd/console/tc_linux.go
  vendor/github.com/containerd/console/tc_openbsd_cgo.go
  vendor/github.com/containerd/console/tc_openbsd_nocgo.go
  vendor/github.com/containerd/console/tc_solaris_cgo.go
  vendor/github.com/containerd/console/tc_solaris_nocgo.go
  vendor/github.com/containerd/console/tc_unix.go
  vendor/github.com/containerd/containerd/.appveyor.yml
  vendor/github.com/containerd/containerd/archive/tar.go
  vendor/github.com/containerd/containerd/archive/tar_opts.go
  vendor/github.com/containerd/containerd/archive/tar_opts_linux.go
  vendor/github.com/containerd/containerd/archive/tar_opts_unix.go
  vendor/github.com/containerd/containerd/archive/tar_opts_windows.go
  vendor/github.com/containerd/containerd/archive/tar_unix.go
  vendor/github.com/containerd/containerd/archive/tar_windows.go
  vendor/github.com/containerd/containerd/image.go
  vendor/github.com/containerd/containerd/images/handlers.go
  vendor/github.com/containerd/containerd/oci/spec.go
  vendor/github.com/containerd/containerd/oci/spec_opts.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/modules.txt
Labels: kind/design, kind/feature, priority/important-longterm

#359 Switch to using weaveworks/gitops-toolkit
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/cleanup

#361 Release 0.5.2
  docs/installation.md
  pkg/runtime/docker/client.go
  pkg/runtime/docker/port.go
Labels: area/releasing, kind/cleanup

#362 update ignite version to v0.5.1
  docs/installation.md
Labels: kind/documentation

#364 Update the master branch with v0.5.2 info
  CHANGELOG.md
  docs/installation.md
  docs/releases/v0.5.2.md
Labels: kind/cleanup

#368 containerd backend improvements
  pkg/container/firecracker.go
  pkg/runtime/containerd/client.go
  pkg/runtime/containerd/io.go
  vendor/modules.txt
Labels: kind/enhancement, kind/feature

#370 CNI: create the config directory and add Ignite config if not configured
  pkg/network/cni/cni.go
  pkg/util/fs.go
Labels: kind/enhancement, kind/feature

#369 fix unnecessary commit
  pkg/gitops/gitdir/gitdir.go
Labels: kind/bug, priority/important-soon

#371 Make containerd the default runtime and CNI the default network plugin
  docs/cli/ignite/ignite.md
  docs/cli/ignite/ignite_attach.md
  docs/cli/ignite/ignite_completion.md
  docs/cli/ignite/ignite_create.md
  docs/cli/ignite/ignite_exec.md
  docs/cli/ignite/ignite_image.md
  docs/cli/ignite/ignite_image_import.md
  docs/cli/ignite/ignite_image_ls.md
  docs/cli/ignite/ignite_image_rm.md
  docs/cli/ignite/ignite_inspect.md
  docs/cli/ignite/ignite_kernel.md
  docs/cli/ignite/ignite_kernel_import.md
  docs/cli/ignite/ignite_kernel_ls.md
  docs/cli/ignite/ignite_kernel_rm.md
  docs/cli/ignite/ignite_kill.md
  docs/cli/ignite/ignite_logs.md
  docs/cli/ignite/ignite_ps.md
  docs/cli/ignite/ignite_rm.md
  docs/cli/ignite/ignite_rmi.md
  docs/cli/ignite/ignite_rmk.md
  docs/cli/ignite/ignite_run.md
  docs/cli/ignite/ignite_ssh.md
  docs/cli/ignite/ignite_start.md
  docs/cli/ignite/ignite_stop.md
  docs/cli/ignite/ignite_version.md
  docs/cli/ignite/ignite_vm.md
  docs/cli/ignite/ignite_vm_attach.md
  docs/cli/ignite/ignite_vm_create.md
  docs/cli/ignite/ignite_vm_kill.md
  docs/cli/ignite/ignite_vm_logs.md
  docs/cli/ignite/ignite_vm_ps.md
  docs/cli/ignite/ignite_vm_rm.md
  docs/cli/ignite/ignite_vm_run.md
  docs/cli/ignite/ignite_vm_ssh.md
  docs/cli/ignite/ignite_vm_start.md
  docs/cli/ignite/ignite_vm_stop.md
  docs/cli/ignited/ignited.md
  docs/cli/ignited/ignited_completion.md
  docs/cli/ignited/ignited_daemon.md
  docs/cli/ignited/ignited_gitops.md
  docs/cli/ignited/ignited_version.md
  pkg/providers/providers.go
Labels: area/ecosystem, kind/api-change, kind/refactor

#373 Move VM network removal to logically correct place
  pkg/network/cni/cni.go
  pkg/operations/remove.go
  pkg/operations/start.go
  pkg/runtime/containerd/client.go
Labels: kind/bug, priority/important-soon

#374 GitOps: only change the VM state if it differs from the current one
  pkg/operations/reconcile/reconcile.go
Labels: kind/bug, kind/enhancement

#375 Implement hostPort support with CNI
  pkg/network/cni/cni.go
  pkg/network/docker/docker.go
  pkg/network/types.go
  pkg/operations/remove.go
  pkg/operations/start.go
Labels: kind/enhancement

#376 Implement cleanup of CNI networks using the default bridge
  go.mod
  go.sum
  pkg/network/cni/cni.go
  pkg/operations/start.go
  vendor/github.com/containernetworking/plugins/LICENSE
  vendor/github.com/containernetworking/plugins/pkg/ip/addr_linux.go
  vendor/github.com/containernetworking/plugins/pkg/ip/cidr.go
  vendor/github.com/containernetworking/plugins/pkg/ip/ipforward_linux.go
  vendor/github.com/containernetworking/plugins/pkg/ip/ipmasq_linux.go
  vendor/github.com/containernetworking/plugins/pkg/ip/link_linux.go
  vendor/github.com/containernetworking/plugins/pkg/ip/route_linux.go
  vendor/github.com/containernetworking/plugins/pkg/ip/utils_linux.go
  vendor/github.com/containernetworking/plugins/pkg/ns/README.md
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
  vendor/github.com/containernetworking/plugins/pkg/utils/hwaddr/hwaddr.go
  vendor/github.com/containernetworking/plugins/pkg/utils/utils.go
  vendor/github.com/coreos/go-iptables/LICENSE
  vendor/github.com/coreos/go-iptables/NOTICE
  vendor/github.com/coreos/go-iptables/iptables/iptables.go
  vendor/github.com/coreos/go-iptables/iptables/lock.go
  vendor/github.com/safchain/ethtool/.gitignore
  vendor/github.com/safchain/ethtool/.travis.yml
  vendor/github.com/safchain/ethtool/LICENSE
  vendor/github.com/safchain/ethtool/Makefile
  vendor/github.com/safchain/ethtool/README.md
  vendor/github.com/safchain/ethtool/ethtool.go
  vendor/github.com/safchain/ethtool/ethtool_cmd.go
  vendor/github.com/safchain/ethtool/ethtool_msglvl.go
  vendor/modules.txt
Labels: kind/enhancement

#377 CNI: fix conflist loading, avoid name collision and nil allocation
  pkg/network/cni/cni.go
Labels: kind/bug, kind/enhancement

#378 Update the docs for v0.6.0
  Makefile
  README.md
  docs/awesome.md
  docs/declarative-config.md
  docs/dependencies.md
  docs/footloose.md
  docs/gitops.md
  docs/installation.md
  docs/networking.md
  docs/roadmap.md
  docs/usage.md
Labels: kind/documentation
