Repository weaveworks/ignite, pull requests merged in 2020-11, with the labels that each got.

#717 Add OS image release workflow
  .github/workflows/release-os-images.yml
  images/Makefile
Labels: area/releasing

#719 workflow: Upload release assets
  .github/workflows/upload-release-assets.yml
  Makefile
  hack/release-common.sh
  images/kernel/upgrade-config.sh
Labels: area/releasing

#722 Add kernel image release workflow
  .github/workflows/release-kernel-images.yml
  images/kernel/Makefile
Labels: area/releasing

#725 Build kernel from a specific git tag
  images/kernel/Dockerfile
  images/kernel/Makefile
  images/kernel/builder/Dockerfile
  images/kernel/upgrade-config.sh
Labels: kind/enhancement

#730 workflow/release-os-images: Disable fail-fast
  .github/workflows/release-os-images.yml
Labels: area/releasing

#735 Fix vm stop-start with default providers
  cmd/ignite/run/start.go
  e2e/vm_lifecycle_test.go
Labels: kind/bug

#731 Bump CNI to v0.8.7
  .travis.yml
  docs/arm.md
  docs/dependencies.md
  docs/installation.md
Labels: area/dependency
