Repository weaveworks/ignite, pull requests merged in 2020-08, with the labels that each got.

#651 Add runtime and network info in VM object
  cmd/ignite/run/cp.go
  cmd/ignite/run/inspect_test.go
  cmd/ignite/run/ps.go
  cmd/ignite/run/ps_test.go
  cmd/ignite/run/ssh.go
  cmd/ignite/run/start.go
  cmd/ignite/run/testdata/output/inspect-json.txt
  cmd/ignite/run/testdata/output/inspect-yaml.txt
  docs/api/ignite_v1alpha2.md
  docs/api/ignite_v1alpha3.md
  go.mod
  pkg/apis/ignite/types.go
  pkg/apis/ignite/v1alpha2/conversion.go
  pkg/apis/ignite/v1alpha2/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha3/types.go
  pkg/apis/ignite/v1alpha3/zz_generated.conversion.go
  pkg/apis/ignite/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/ignite/zz_generated.deepcopy.go
  pkg/dmlegacy/vm.go
  pkg/openapi/openapi_generated.go
  pkg/operations/start.go
  vendor/modules.txt
Labels: api/v1alpha3, kind/api-change

#652 Exec blkid to getUUID() instead of relying on udevd symlinks
  pkg/dmlegacy/fstab.go
Labels: area/dependency, area/runtime, kind/enhancement

#654 Configure dmsetup to fallback to managing device nodes without udevd
  pkg/dmlegacy/cleanup/deactivate.go
  pkg/dmlegacy/loopdev.go
  pkg/dmlegacy/snapshot.go
  pkg/dmlegacy/vm.go
  pkg/operations/remove.go
  pkg/operations/start.go
Labels: area/dependency, area/runtime, kind/enhancement, kind/refactor

#653 Fix in-container device nodes for containerd runtime
  e2e/README.md
  e2e/run_test.go
  e2e/run_volume_test.go
  pkg/runtime/containerd/client.go
Labels: area/runtime, kind/bug

#667 docs/installation: set VM status.running to true
  docs/installation.md
Labels: documentation/better-examples

#671 Update installation instructions for Amazon Linux
  docs/installation.md
Labels: documentation/improvement

#678 Fixes command in docs
  docs/dependencies.md
Labels: documentation/improvement

#680 Add dependabot for github-actions and gomod
  .github/dependabot.yml
Labels: area/dependency
