Repository weaveworks/ignite, pull requests merged in 2020-09, with the labels that each got.

#676 Update ignite help, image and kernel to no longer require root
  cmd/ignite/cmd/root.go
Labels: kind/enhancement

#688 Add VM name validation
  e2e/config_test.go
  e2e/cp_test.go
  e2e/run_test.go
  e2e/run_volume_test.go
  e2e/vm_exec_test.go
  e2e/vm_lifecycle_test.go
  pkg/apis/ignite/validation/validation.go
Labels: kind/enhancement

#689 Add ignited gitops mode e2e test
  .travis.yml
  e2e/gitops_test.go
  e2e/util/command.go
Labels: area/testing

#691 Fix CNI portmapping cleanup
  e2e/portmap_test.go
  pkg/network/cni/cni.go
  pkg/network/docker/docker.go
  pkg/network/types.go
  pkg/operations/remove.go
Labels: area/networking
