Repository weaveworks/ignite, pull requests merged in 2021-07, with the labels that each got.

#855 Update docs and test data with v1alpha4 API
  cmd/ignite/run/testdata/input/apply-vm-config-invalid.yaml
  cmd/ignite/run/testdata/input/apply-vm-config.json
  cmd/ignite/run/testdata/input/apply-vm-config.yaml
  cmd/ignite/run/testdata/input/create-config-no-name.yaml
  cmd/ignite/run/testdata/input/rm-no-name-uid.yaml
  cmd/ignite/run/testdata/input/rm-vm1.yaml
  docs/api/index.md
  docs/declarative-config.md
  docs/gitops.md
  docs/ignite-configuration.md
  docs/installation.md
  docs/my-vm.yaml
Labels: documentation/better-examples

#854 SIGSEGV with metadata from older version of ignite
  cmd/ignite/run/ps.go
Labels: kind/bug

#858 Update default kernel to 5.10.51
  cmd/ignite/run/testdata/output/apply-vm-config-empty.json
  docs/cli/ignite/ignite_create.md
  docs/cli/ignite/ignite_run.md
  docs/cli/ignite/ignite_vm_create.md
  docs/cli/ignite/ignite_vm_run.md
  docs/declarative-config.md
  docs/footloose.md
  docs/installation.md
  docs/usage.md
  e2e/multinet_test.go
  e2e/util/setup-private-registry.sh
  pkg/apis/meta/v1alpha1/image_test.go
  pkg/constants/kernel.go
Labels: area/kernels
