Repository weaveworks/ignite, pull requests merged in 2021-03, with the labels that each got.

#787 ps: Add out-of-date VM manifest status indicator
  cmd/ignite/run/ps.go
  e2e/vm_ps_test.go
Labels: area/UX

#796 Use declarative port mappings and copy files values when CLI flags are empty
  cmd/ignite/run/create.go
  cmd/ignite/run/create_test.go
Labels: kind/bug

#798 Upgrade kernel versions
  .github/workflows/release-kernel-images.yml
  images/kernel/Makefile
  images/kernel/generated/config-amd64-4.14.223
  images/kernel/generated/config-amd64-4.19.178
  images/kernel/generated/config-amd64-5.4.102
  images/kernel/generated/config-arm64-4.14.223
  images/kernel/generated/config-arm64-4.19.178
  images/kernel/generated/config-arm64-5.4.102
  images/kernel/versioned/config-amd64-4.14.223
  images/kernel/versioned/config-amd64-4.19.178
  images/kernel/versioned/config-amd64-5.4.102
  images/kernel/versioned/config-arm64-4.14.223
  images/kernel/versioned/config-arm64-4.19.178
  images/kernel/versioned/config-arm64-5.4.102
Labels: area/kernels

#799 Bump ignite-spawn base image to Alpine to 3.13
  Makefile
Labels: area/images

#802 Add k3s to the release-os-image gh workflow
  .github/workflows/release-os-images.yml
Labels: area/releasing

#800 Bump k3s to v1.20.4+k3s1
  images/Makefile
Labels: area/images

#797 Upgrade firecracker to v0.22.4
  Dockerfile
  docs/installation.md
  hack/FIRECRACKER_VERSION
Labels: area/dependency

#807 Handle error when the backend storage is uninitialized
  cmd/ignite/run/images.go
  cmd/ignite/run/kernels.go
  cmd/ignite/run/ps.go
Labels: kind/enhancement

#808 ps: Mark VM with * when the state can't be confirmed
  cmd/ignite/run/ps.go
Labels: kind/enhancement

#809 runtime: Handle error when container not found
  pkg/runtime/containerd/client.go
  pkg/runtime/docker/client.go
Labels: area/UX, kind/enhancement

#791 Fix containerd cont delete when task load or delete fails
  pkg/runtime/containerd/client.go
Labels: area/runtime, kind/bug

#812 Change the log level in RemoveContainer to debug
  pkg/runtime/containerd/client.go
Labels: area/runtime
