Repository weaveworks/ignite, pull requests merged in 2021-02, with the labels that each got.

#766 Allow clean builds from tarballs
  hack/ldflags.sh
Labels: area/releasing

#778 ps: Handle error when the backend storage is uninitialized
  cmd/ignite/run/ps.go
  cmd/ignite/run/ps_test.go
Labels: area/UX, kind/enhancement

#779 runtime: Get containerd container task status
  pkg/runtime/containerd/client.go
  pkg/runtime/containerd/client_test.go
Labels: area/runtime, kind/enhancement
